version: '3'

services:
  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - "8080:8080"  # Expose Tomcat directly for debugging (optional)
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
